site_name: Evals and Inference
theme:
    name: simple-blog # readthedocs
nav:
  - Home: index.md
  - Posts:
      - Basics of LLM Evaluations: llm-evaluations.md
      - Evals by Clementine: evaluation-principles-by-Clementine.md
      - Evals by Jason Wei: evaluation-by-Jason-Wei.md
      - Research Paper on Healthcare Bias in The Pile: Research Paper on Healthcare Bias in The Pile.md
      - BERTscore and friends:  BERTscore and friends.md
      - AI Evaluation Tools and Libraries: AI-Evaluation-Tools-and-Libraries.md
  
