site_name: Evals and Inference
theme:
    name: simple-blog # readthedocs
nav:
  - Home: index.md
  - Basics of LLM evaluations: llm-evaluations.md
  - Principles by Clementine: evaluation-principles-by-Clementine.md
